### ISSUE TITLE
exporting the `packageResolve` function

### ISSUE THREAD

**Issue by sheerlox** [wooorm/import-meta-resolve#18]
Hey there :wave: Thanks for developing this great package!

I am working on an ESM version of [`import-from`](https://www.npmjs.com/package/import-from) (*ingeniously* named [`import-from-esm`](https://www.npmjs.com/package/import-from-esm)), for which I needed to emulate `require`'s behavior using ESM dynamic `import`.

I found a function (`packageResolve`) in your library that saved me 99% of the work, and by using it I don't have to implement `node_modules` tree traversal, export maps resolution, etc...

Because that function isn't exported by your package, I have copied the sources (and license) from `import-meta-resolve/lib/`, exported the `packageResolve` function, removed the `resolve` & `moduleResolve` functions, and pruned unused code.

As discussed on https://github.com/semantic-release/release-notes-generator/pull/544#issuecomment-1793755195, it would be best to directly use your library for updates and security concerns, if you'd agree to export the `packageResolve` function (without necessarily documenting it).

Please let me know if you'd be okay with that, or if there are any concerns on your mind!

**Comment by wooorm** [comment]
Yo Pierre!

I’m not super opposed to exposing this.

However, now that `import.meta.resolve` in Node is a [release candidate](https://nodejs.org/api/esm.html#importmetaresolvespecifier), I expect it to be unflagged soonish. If that happens, that would likely/hopefully be backported to v18. Which is EOL at 2025-04-30, at which point this package is no longer needed, at which point you’d need a maintained version.

So perhaps pushing for https://github.com/nodejs/node/issues/49445 I think might be better?

Anyway, feel free to PR this for now.
And, given 49445, perhaps return the folder URL (as a string) instead of the package.json URL? That would make it useful more broadly. And then we kinda polyfill that `import.meta` idea!

**Comment by sheerlox** [comment]
Thank you for your swift response, and for pointing me to https://github.com/nodejs/node/issues/49445!

After reading the whole thread this morning, I added missing tests on my library and started a little refactoring: it turns out `moduleResolve` does the job for my use case, with the added benefit of now supporting import maps.

Thank you for your guidance :smile:
