### ISSUE TITLE
Enabling usage of this package in an eslint plugin

### ISSUE THREAD

**Issue by giltayar** [wooorm/import-meta-resolve#2]
Context: I'm trying to help revive [eslint-plugin-node](https://www.npmjs.com/package/eslint-plugin-node), using a fork someone created (https://www.npmjs.com/package/eslint-plugin-node).

The first issue I wanted to fix is that `eslint-plugin-node` errs on packages that have no `main` in their`package.json`. This is because it uses @ljharb's `resolve` package which doesn't yet cover the new `exports` field. I looked for a replacement package, and yours fit the bill.

Unfortunately, it's ESM-only, and ESLint is CJS. And... I can't `await import` it, because ESLint doesn't support async plugins anywhere in their API (at least I couldn't find anything).

So... any chance you would be willing to accept a PR that turns this into a dual-mode package? I know you're very much on the ESM-only bandwagon, but... maybe? I would do it the usual way: a build process to transpile it into CJS using rollup or babel, and package it as dual-mode. Should work.

(and, yes, the API is async, but I noticed that it isn't _really_, so I could create a sync version)

**Comment by nicolo-ribaudo** [comment]
I recently wanted to add this package as a dependency of Babel, and we are probably going to inline it in our source code so that we can compile it to CJS until we are ready to migrate to ESM: https://github.com/babel/babel/pull/14110/files#diff-754bd25a9bce7737d21fa0a30ade059884e89f9e4298c6c16ee25ad4b21e7651R531

@giltayar Maybe you could do something similar?

Btw, an alternative is to do something like https://giuseppegurgone.com/synchronizing-async-functions/ so that you can use dynamic import to load this package and also use the async resolution algorithm, while still being able to use it in a (cjs, sync) ESLint plugin. We do something similar in `@babel/eslint-parser`: ESLint only allows synchronous parser, but we need to run it asynchronously so we moved it to a separate worker (https://github.com/babel/babel/pull/13199).

**Comment by wooorm** [comment]
Hey both!

I think we’ve reached a point where CJS users can create vendored versions of ESM packages they use? E.g.,:

```sh
npx esbuild import-meta-resolve --bundle --platform=node --outfile=vendor/import-meta-url.cjs
```

I think this issue also points to an old problem in esbuild: it should really start supporting async things at some point?

**Comment by ljharb** [comment]
It's generally a very bad idea to transpile code one didn't author.

**Comment by wooorm** [comment]
What is this nonsense. Esbuild, swc, webpack, whathaveyou disagree.

@ljharb i understand you were pinged but I don't think us having another ESM discussion is fruitful.

**Comment by ljharb** [comment]
@wooorm this isn't an ESM discussion, it's a "transpiling has caveats that only the author can understand if they apply or not" discussion. There will never be a point at which that isn't true, because the JS language doesn't permit that confidence.

**Comment by wooorm** [comment]
Right, I'm against compiling esm to cjs too?

---

Though, I assume that an eslint plugin vendoring a dependency with a good amount of tests won't pose any problems?

**Comment by ljharb** [comment]
Whether you compile it yourself or not is the ESM discussion we don't have to have :-) I'm saying that if you don't, nobody else should.

**Comment by giltayar** [comment]
@ljharb @wooorm From my point of view this isn't a theoretical discussion. It's a practical one to solve a specific problem I have. And the three suggestions here, from @wooorm and @nicolo-ribaudo, seem like good practical solutions (although the "synchronized worker" sounds a bit too heavy for use in an eslint plugin).
